name: CI
run-name: CI
permissions: read-all
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run linter
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
      - name: Run tests
        run: go test -count=1 -race ./...
  md-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run markdownlint1
        uses: avto-dev/markdown-lint@v1
        with:
          args: "README.md"
